# For public, HTTPS servers.
version: '2'
services:
  rabbit:
    environment:
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq
    restart: on-failure
    network_mode: bridge

  postgres:
    env_file:
      - ./envfile.local.txt
    restart: on-failure
    network_mode: bridge
    ports:
      - 0.0.0.0:5432:5432

  mongo:
    environment:
      - MONGO_DATA=/srv/db
    env_file:
      - ./envfile.local.txt
    restart: on-failure
    network_mode: bridge

  kobocat:
    env_file:
      - ./envfile.local.txt
      - ./envfiles/aws.txt
      - ./envfiles/external_services.txt
      - ./envfiles/kobocat.txt
      - ./envfiles/nginx.txt
      - ./envfiles/smtp.txt
    links:
      - rabbit
      - mongo
      - postgres
      - kpi
    environment:
      - ENKETO_PROTOCOL=https
    restart: on-failure
    network_mode: bridge
    volumes:
      - ../src/custom_kobocat_theme:/srv/src/custom_kobocat_theme
    environment:
      - DJANGO_SETTINGS_MODULE=custom_kobocat_theme.settings
      - PYTHONPATH=/srv/src/kobocat:/srv/src/custom_kobocat_theme
      - DEBUG=True
    ports:
      - 9001:8001

  kpi:
    env_file:
      - ./envfile.local.txt
      - ./envfiles/aws.txt
      - ./envfiles/external_services.txt
      - ./envfiles/kpi.txt
      - ./envfiles/nginx.txt
      - ./envfiles/smtp.txt
    environment:
      - DJANGO_SETTINGS_MODULE=custom_kpi_theme.settings
      - PYTHONPATH=/srv/src/kpi:/srv/src/custom_kpi_theme
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO, https
    volumes:
      - ../src/custom_kpi_theme:/srv/src/custom_kpi_theme
    links:
      - postgres
      - rabbit
      - mongo
    restart: on-failure
    network_mode: bridge

  nginx:
    env_file:
      - ./envfile.local.txt
      - ./envfiles/nginx.txt
      - ./envfiles/kobocat.txt
      - ./envfiles/kpi.txt
    environment:
      - NGINX_CONFIG_FILE_NAME=nginx_site_http.conf
      - TEMPLATED_VAR_REFS=$${PUBLIC_DOMAIN_NAME} $${KOBOFORM_PUBLIC_SUBDOMAIN} $${KOBOCAT_PUBLIC_SUBDOMAIN} $${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}
    ports:
      - 80:80
      - 443:443
      - 8000:9000 # KPI
      - 8001:9001 # KoBoCAT
      - 8005:9005 # Enketo Express
    links:
      - kobocat
      - kpi
      - enketo_express
    restart: on-failure
    network_mode: bridge

  # Adapted from https://github.com/${REPO_NAME}/${REPO_PREFIX}_enketo-express/blob/docker/docker-compose.yml.
  enketo_express:
    env_file:
      - ./envfile.local.txt
      - ./envfiles/external_services.txt
    links:
      - redis_main
      - redis_cache
    restart: on-failure
    network_mode: bridge

  # Adapted from https://github.com/${REPO_NAME}/${REPO_PREFIX}_enketo-express/blob/docker/docker-compose.yml.
  redis_main:
    # Map our "main" Redis config into the container.
    restart: on-failure
    network_mode: bridge

  # Adapted from https://github.com/${REPO_NAME}/${REPO_PREFIX}_enketo-express/blob/docker/docker-compose.yml.
  redis_cache:
    # Map our "cache" Redis config into the container.
    restart: on-failure
    network_mode: bridge
