# For public, HTTPS servers.
# Note that you need your certificates to be verified by public CA
# If you generate local certificates, some features doesn't work because
# of unsecure requests warning.
version: '2'
services:
  kobocat:
    volumes:
      - ./backups/backups-kobocat:/srv/backups
      - ../src/kobocat:/srv/src/kobocat
      - ../src/kobocat-template:/srv/src/kobocat-template
      # These needs to be a verifiable cert from public CA
      - ./secret/ssl.crt:/usr/local/share/ca-certificates/ssl.crt
    environment:
      KOBOCAT_DJANGO_DEBUG: 'True'
      USE_ENV_VAR: 'True'
      ENKETO_URL: https://enketo.kobotoolbox.test
      KOBOCAT_URL: https://kobocat.kobotoolbox.test
      KOBOFORM_URL: https://koboform.kobotoolbox.test
      KOBOCAT_INTERNAL_URL: https://kobocat.kobotoolbox.test
      CSRF_COOKIE_DOMAIN: .kobotoolbox.test
      DJANGO_ALLOWED_HOSTS: .kobotoolbox.test
      REQUESTS_CA_BUNDLE: '/usr/local/share/ca-certificates/ssl.crt'
      ENKETO_PROTOCOL: https

  kpi:
    volumes:
      - ../src/kpi:/srv/src/kpi
      - ./secret/ssl.crt:/usr/local/share/ca-certificates/ssl.crt
    environment:
      KPI_DJANGO_DEBUG: 'True'
      USE_ENV_VAR: 'True'
      ENKETO_URL: http://enketo.kobotoolbox.test
      KOBOCAT_URL: http://kobocat.kobotoolbox.test
      KOBOFORM_URL: http://koboform.kobotoolbox.test
      KOBOCAT_INTERNAL_URL: http://kobocat.kobotoolbox.test
      CSRF_COOKIE_DOMAIN: .kobotoolbox.test
      DJANGO_ALLOWED_HOSTS: .kobotoolbox.test
      REQUESTS_CA_BUNDLE: '/usr/local/share/ca-certificates/ssl.crt'
      ENKETO_PROTOCOL: https

  enketo_express:
    volumes:
      - ./secret/ssl.crt:/usr/local/share/ca-certificates/ssl.crt

  postgres:
    volumes:
      - ./backups/backups-postgres:/srv/backups

  mongo:
    volumes:
      - ./backups/backups-mongo:/srv/backups

  nginx:
    environment:
      # Uncomment following line to just Proxy the web server instead of using
      # uWSGI (default settings)
#      KPI_WEB_SERVER: 'PROXY'
#      KOBOCAT_WEB_SERVER: 'PROXY'
      KPI_WEB_SERVER: 'UWSGI'
      KOBOCAT_WEB_SERVER: 'UWSGI'
